# Generated by Django 5.2.17 on 2026-08-26 20:21

import apps.core.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('trader', 'Trader'), ('agent', 'Agent')], max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=40)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('timezone', models.CharField(default='Africa/Addis_Ababa', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=80)),
                ('unit', models.CharField(default='unit', max_length=40)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock_threshold', models.DecimalField(decimal_places=3, default=Decimal('5'), max_digits=18)),
                ('supplier', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.store')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('voided', 'Voided')], default='completed', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=18)),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=18)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.party')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('mobile', 'Mobile money'), ('other', 'Other')], default='cash', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.party')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='core.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('summary', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, upload_to=apps.core.models.report_upload_path)),
                ('excel_file', models.FileField(blank=True, upload_to=apps.core.models.report_upload_path)),
                ('error_message', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.store')),
            ],
            options={
                'ordering': ['-period_end', '-version'],
            },
        ),
        migrations.AddField(
            model_name='party',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='core.store'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low stock'), ('debt', 'Customer debt'), ('report', 'Report'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('event_key', models.CharField(max_length=200)),
                ('entity_type', models.CharField(blank=True, max_length=40)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('viewer', 'Report viewer')], default='cashier', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('payment', 'Payment'), ('credit', 'Credit or loan'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('delta', models.DecimalField(decimal_places=2, max_digits=18)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='core.party')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.payment')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='core.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='core.store')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.store'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_low_stock_threshold', models.DecimalField(decimal_places=3, default=Decimal('5'), max_digits=18)),
                ('prevent_negative_inventory', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_reminder_time', models.TimeField(default='09:00')),
                ('sms_provider', models.CharField(default='console', max_length=50)),
                ('sms_account_number', models.CharField(blank=True, max_length=100)),
                ('automated_reports_enabled', models.BooleanField(default=True)),
                ('daily_report_time', models.TimeField(default='21:00')),
                ('weekly_report_day', models.PositiveSmallIntegerField(default=6, help_text='Monday=0, Sunday=6')),
                ('weekly_report_time', models.TimeField(default='21:00')),
                ('monthly_report_time', models.TimeField(default='21:00')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('opening', 'Opening stock'), ('received', 'Stock received'), ('sale', 'Sale'), ('return', 'Sale return'), ('adjustment', 'Adjustment'), ('damaged', 'Damaged or lost'), ('reversal', 'Reversal')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=18)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.store')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['store', 'product', 'created_at'], name='core_stockm_store_i_9080bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reminder_date', models.DateField()),
                ('message', models.TextField()),
                ('provider', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sms_logs', to='core.party')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('store', 'party', 'reminder_date'), name='one_debt_reminder_per_party_day')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('debt_sms', 'Debt reminder SMS'), ('daily_report', 'Daily report'), ('weekly_report', 'Weekly report'), ('monthly_report', 'Monthly report')], max_length=30)),
                ('period_key', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_job_runs', to='core.store')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'job_type', 'period_key'), name='unique_scheduled_job_period')],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'created_at'], name='core_sale_store_i_25f41a_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'customer', 'created_at'], name='core_sale_store_i_0f45df_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('store', 'idempotency_key'), name='unique_sale_idempotency_per_store'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('store', 'report_type', 'period_start', 'period_end', 'version'), name='unique_report_version'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'name'], name='core_produc_store_i_976d83_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'sku'], name='core_produc_store_i_130c11_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'sku'), name='unique_product_sku_per_store'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['store', 'party', 'created_at'], name='core_paymen_store_i_70c4b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('store', 'idempotency_key'), name='unique_payment_idempotency_per_store'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['store', 'party_type', 'name'], name='core_party_store_i_f1541c_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['store', 'phone'], name='core_party_store_i_7f3c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['store', 'account_number'], name='core_party_store_i_73bbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['store', 'current_balance'], name='core_party_store_i_698b41_idx'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('store', 'party_type', 'phone'), name='unique_party_phone_per_type_store'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['store', 'is_read', 'is_resolved'], name='core_notifi_store_i_bd0c22_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('store', 'event_key'), name='unique_notification_event_per_store'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'store'), name='unique_store_membership'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['store', 'party', 'created_at'], name='core_financ_store_i_c3efcc_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['store', 'created_at'], name='core_financ_store_i_0f9bf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_category_name_per_store'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['store', 'created_at'], name='core_audite_store_i_85aba4_idx'),
        ),
    ]
