# Generated by Django 5.2.17 on 2026-09-01 08:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="company",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="payment",
            name="direction",
            field=models.CharField(choices=[("received", "Payment received"), ("sent", "Payment sent")], default="received", max_length=20),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="overdue_days",
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="transaction_type",
            field=models.CharField(choices=[("sale", "Sale"), ("payment", "Payment"), ("credit", "Credit or loan"), ("adjustment", "Adjustment"), ("purchase", "Purchase"), ("reversal", "Reversal")], max_length=20),
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("color", models.CharField(default="#176B54", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expense_categories", to="core.store")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("expense_date", models.DateField()),
                ("payment_method", models.CharField(choices=[("cash", "Cash"), ("bank", "Bank transfer"), ("mobile", "Mobile money"), ("credit", "Credit"), ("other", "Other")], default="cash", max_length=20)),
                ("description", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_reversed", models.BooleanField(default=False)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="expenses", to=settings.AUTH_USER_MODEL)),
                ("reversed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reversed_expenses", to=settings.AUTH_USER_MODEL)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="core.store")),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="expenses", to="core.expensecategory")),
            ],
            options={"ordering": ["-expense_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="MonthlyBudget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monthly_budgets", to="core.store")),
            ],
            options={"ordering": ["-year", "-month"]},
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("idempotency_key", models.UUIDField(default=uuid.uuid4)),
                ("status", models.CharField(choices=[("completed", "Completed"), ("voided", "Voided")], default="completed", max_length=20)),
                ("purchase_date", models.DateField()),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=18)),
                ("total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=18)),
                ("outstanding", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchases", to=settings.AUTH_USER_MODEL)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="purchases", to="core.store")),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchases", to="core.party")),
            ],
            options={"ordering": ["-purchase_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="financialtransaction",
            name="purchase",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ledger_entries", to="core.purchase"),
        ),
        migrations.AddField(
            model_name="payment",
            name="purchase",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="core.purchase"),
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=180)),
                ("sku", models.CharField(max_length=80)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.001"))])),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.00"))])),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="purchase_items", to="core.product")),
                ("purchase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="core.purchase")),
            ],
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(fields=("store", "name"), name="unique_expense_category_per_store"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["store", "expense_date"], name="core_expens_store_i_4f2b91_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["store", "category", "expense_date"], name="core_expens_store_i_7e4a36_idx"),
        ),
        migrations.AddConstraint(
            model_name="monthlybudget",
            constraint=models.UniqueConstraint(fields=("store", "year", "month"), name="unique_monthly_budget_per_store"),
        ),
        migrations.AddConstraint(
            model_name="monthlybudget",
            constraint=models.CheckConstraint(condition=models.Q(("month__gte", 1), ("month__lte", 12)), name="valid_budget_month"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["store", "purchase_date"], name="core_purcha_store_i_75d024_idx"),
        ),
        migrations.AddIndex(
            model_name="purchase",
            index=models.Index(fields=["store", "supplier", "purchase_date"], name="core_purcha_store_i_df55eb_idx"),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(fields=("store", "idempotency_key"), name="unique_purchase_idempotency_per_store"),
        ),
    ]
